pipeline:
  name: dsvw_pipeline
  identifier: dsvw_pipeline
  projectIdentifier: SonarQube_Test_Project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dsvw_connector
        build: <+input>
  stages:
    - stage:
        name: scan with sq
        identifier: scan_with_sq
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Sonarqube
                  name: Sonarqube scan
                  identifier: Sonarqube_scan
                  spec:
                    mode: orchestration
                    config: default
                    target:
                      type: repository
                      detection: auto
                    advanced:
                      log:
                        level: info
                      fail_on_severity: low
                    auth:
                      access_token: <+secrets.getValue("SQ_MAY_USER")>
                      domain: <+secrets.getValue("sonarqube_url")>
                      ssl: true
                    tool:
                      project_key: dsvw_app
